accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='user_registration'),
    path('login/', views.LoginView.as_view(), name='user_login'),
    path('logout/', views.LogoutView.as_view(), name='user_logout'),
    path('user_profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('edit/', views.AccountEditView.as_view(), name='account_edit'),

    # password reset urls
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),

    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_pass_form.html'), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'),
         name='password_reset',),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view
         (template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('you-are-finally-awake/', admin.site.urls), # Real admin URL
    path('captcha/', include('captcha.urls')), # django-simple-captcha urls
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('skills/', include('skills.urls', namespace='skills')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils.text import slugify
from django.urls import reverse


class MyAccountManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("Email address is required!")
        user = self.model(
            email=self.normalize_email(email)
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.is_student = True
        user.is_teacher = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):

    phone_number = models.CharField(verbose_name='Phone Number', max_length=11, unique=True, null=True, blank=True)
    username = models.CharField(max_length=250, unique=True, null=True, blank=True)
    email = models.CharField(verbose_name='Email', max_length=250, unique=True, null=True)
    first_name = models.CharField(verbose_name="First Name", max_length=200, null=True, blank=True)
    last_name = models.CharField(verbose_name="Last Name", max_length=200, null=True, blank=True)
    

    date_joined = models.DateTimeField(verbose_name="Date Joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="Last Login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = MyAccountManager()

    def __str__(self):
        return f"{self.email}"

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_lable):
        return True

    def get_absolute_url(self):
        return reverse('courses:teacher_details', args=(self.id, self.slug))

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from accounts.models import Account
from django.utils.translation import gettext_lazy as _
from django.core.validators import validate_email, EmailValidator
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label="", max_length=250, required=True, widget=forms.EmailInput())
    password1 = forms.CharField(label="", max_length=250, required=True, widget=forms.PasswordInput())

    captcha = CaptchaField()

    class Meta:
        model = Account
        fields = ('email', 'password1')

        # to override djangos error messages
        error_messages = {
            'email': {
                'invalid': 'لطفا ایمیل معتبر وارد کنید',
                'unique': 'این ایمیل قبلا استفاده شده است',
                'required': 'ایمیل الزامی است',
            },
        }

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        # password repeat field remove
        # del self.fields['password2']

        self.fields['password1'].help_text = "رمز عبور شما باید حداقل 8 کرکتر باشد"

    def clean_email(self):
        email = self.cleaned_data['email']
        try: 
            validate_email(email)
        except ValidationError:
            raise forms.ValidationError('لطفا ایمیل معتبر وارد کنید', code="invalid")

        user = Account.objects.filter(email=email).exists()
        if user:
            raise forms.ValidationError('این ایمیل قبلا استفاده شده است', code="unique")
          
        return email
    
    def clean_password1(self):
        password = self.cleaned_data['password1']
        
        return password

class UserLoginForm(forms.ModelForm):

    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    captcha = CaptchaField()

    class Meta:
        model = Account
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data.get('email')
            password = self.cleaned_data.get('password')
            user = authenticate(email=email, password=password)
            if not user or not user.is_active:
                # massage for invalid login
                raise forms.ValidationError("نام کاربری یا رمز عبور اشتباه است.")
            return self.cleaned_data

    def login(self, request):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        return user


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'username', 'phone_number', 'email')
        labels = {
            'username': _('نام کاربری'),
            'phone_number': _('شماره همراه'),
            'email': _('ایمیل'),
            'first_name': _('نام'),
            'last_name': _('نام خانوادگی'),
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control my-3'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control my-3'}),
            'email': forms.EmailInput(attrs={'class': 'form-control my-3'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control my-3'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control my-3'}),
        }        

    def clean_username(self):
        username = self.cleaned_data['username']
        if username and self.is_valid():
            try:
                account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
            except Account.DoesNotExist:
                return username
            raise forms.ValidationError('Username "%s" already exists!' % account.username)
        return username

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if phone_number and self.is_valid():
            try:
                account = Account.objects.exclude(pk=self.instance.pk).get(phone_number=phone_number)
            except Account.DoesNotExist:
                return phone_number
            raise forms.ValidationError('Phone number "%s" already exists!' % account.phone_number)
        return phone_number
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if email and self.is_valid():
            try:
                account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
            except Account.DoesNotExist:
                return email
            raise forms.ValidationError('Email "%s" already exists!' % account.email)
        return email

accounts/views.py
from typing import Any
from django import http
from django.shortcuts import render, redirect
from . import forms
from django.contrib.auth import login, authenticate, logout
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from courses.models import *
from accounts.models import *


class UserRegistrationView(View):
    form_class = forms.RegistrationForm
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, "حساب کاربری شما با موفقیت ایجاد شد. برای رزرو کلاس به صفحه اصلی مراجعه کنید.", 'success')
            login(request, user)
            return redirect('accounts:user_profile')
        
        return render(request, 'accounts/register.html', {'form': form})

    def get(self, request):
        form = self.form_class()
        return render(request, 'accounts/register.html', {'form': form})


class LoginView(View):
    form_class = forms.UserLoginForm

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def post(self, request):
        form = self.form_class(request.POST or None)
        if form.is_valid():
            user = form.login(request)
            if user:
                login(request, user)
                if self.next:
                    return redirect(self.next)
                
                return redirect('home:home')
        return render(request, 'accounts/login.html', {'form': form})

    def get(self, request):
        form = self.form_class()
        return render(request, 'accounts/login.html', {'form': form})


class LogoutView(View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        logout(request)
        return redirect('home:home')
    

class UserProfileView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'  # login Url for LoginRequiredMixin

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    
    def setup(self, request: http.HttpRequest, *args: Any, **kwargs: Any) -> None:
        self.courses_instance = request.user.courses.all()
        return super().setup(request, *args, **kwargs)
    
    def get(self, request):
        context = {'courses': self.courses_instance}        
        return render(request, 'accounts/user_profile.html', context)


class AccountEditView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'  # login Url for LoginRequiredMixin
    form_class = forms.AccountEditForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def post(self, request):
        form = self.form_class(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "اطلاعات شما با موفقیت تغییر کرد.", 'success')
            return redirect('accounts:account_details')
        return render(request, 'accounts/account_edit.html', {'form': form})

    def get(self, request):
        form = self.form_class(instance=request.user)
        return render(request, 'accounts/account_edit.html', {'form': form})

accounts/templates/accounts/account_details.html
{% extends 'base.html' %}

{% block content %}
    <head>
        <title>Profile</title>
    </head>
    <div class="contailer-fluid">
        <div class="row">
            {% include 'inc/account_details_sidebar.html' %}
            <div class="col border border-primary">
                <h3>پنل کاربری</h3>
                <hr>
                <p> نام کاربری : {{ user.username }}</p>
                <p>شماره تلفن همراه : {{ user.phone_number }}</p>
                <p>ایمیل : {{ user.email }}</p>
            </div>

        </div>
    </div>


{% endblock %}

accounts/templates/accounts/account_edit.html
{% extends 'accounts/profile_base.html' %}

{% block profile_content %}
    {% block titel %}
        <title>ویرایش اطلاعات کاربری</title>
    {% endblock %}
    <div class="d-flex m-4 justify-content-center">
        <form method="post" class="d-flex flex-column text-center m-auto" novalidate> {% csrf_token %}
            <h5 class="mb-3">ویرایش اطلاعات کاربری</h5>
            <hr>
            {{ form }}
            <button class="btn btn-primary my-3" type="submit">ثبت تغییرات</button>
        </form>
    </div>


{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
    {% block titel %}
        <title>ورود به حساب کاربری</title>
    {% endblock %}
    <div class="d-flex flex-column justify-content-center" style="margin-top: 100px">
      <main class="form-signin w-100 m-auto text-center" style="width: 100%">
          <h5 class="mb-3 fw-normal text-center">ورود به حساب کاربری</h5>
          <hr class="login-register-hr">
          <form class="" method="post" novalidate style="width: 100%">
              {% csrf_token %}
              
              {% render_field form.email class="form-control my-2" placeholder="ایمیل" %}
              <small class="my-2" style="color: red;">{{ form.email.errors }}</small>
              
              {% render_field form.password class="form-control my-2" placeholder="رمز عبور" %}
              <small class="my-2" style="color: red; list-style: none;">{{ form.password.errors }}</small>

              <small class="my-2" style="color: gray;">{{ form.password.help_text }}</small>
              <div class="captcha-field">
                {% render_field form.captcha class="form-control form-sm my-2" placeholder="لطفا کد امنیتی را وارد کنید" %}
              </div>
              <button class="w-100 btn btn-primary" type="submit">ورود</button>
              <a href="{% url 'accounts:user_registration' %}" class="btn btn-outline-secondary w-100 mt-2">ثبت نام</a>
              <hr>
              <a href="{% url 'accounts:password_reset' %}" style="text-decoration: none; color: cornflowerblue;">رمز عبورم را فراموش کردم</a>
          </form>
      </main>
  </div>
    <style>
        .form-signin {
          max-width: 330px;
          padding: 1.5rem;
        }
        .form-signin:focus-within {
          z-index: 2;
        }

    </style>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'accounts/profile_base.html' %}

{% block profile_content %}
<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin-top: 56px;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>
{% block titel %}
    <title>تعویض رمز عبور</title>
{% endblock %}
<div class="d-flex flex-column justify-content-center" style="margin-top: 100px">
    <form method="POST" class="form-signin text-center m-auto">{% csrf_token %}
        <h5 class="mb-3">تعویض رمز عبور</h5>
        <input name="old_password" class="form-control" placeholder="رمز عبور فعلی" type="password" id="id_old_password" required="true">
        <input name="new_password1" class="form-control" placeholder="رمز عبور جدید" type="password" id="id_new_password1" required="true">
        <input name="new_password2" class="form-control" placeholder="تایید رمز عبور جدید" type="password" id="id_new_password2" required="true">

        {% for field in form %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        {% endfor %}
        <button class="btn btn-primary btn-block" type="submit">تایید</button>
    </form>
</div>




{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'base.html' %}

{% block content %}

    {% block titel %}
        <title>تعویض رمز عبور</title>
    {% endblock %}
<div class="container" style="margin-top: 100px">
	<div class="d-flex flex-column">
		<h5 class="m-auto">رمز عبور شما با موفقیت تعویض شد.</h5>
        <br>
        <p class="text-center">بازگشت به <a href="{% url "accounts:account_details" %}">حساب کاربری</a></p>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}
    <head>
    <title>ریست رمز عبور</title>
    </head>

<div class="container" style="margin-top: 100px">
	<div class="d-flex flex-column">
		<p class="m-auto">رمز عبور شما با موفقیت ریست شد. اکنون می توانید <a href="{% url 'accounts:user_login' %}">وارد</a> شوید.</p>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

    <head>
    <title>ایمیل ارسال شد</title>
    </head>
<div class="container" style="margin-top: 100px">

	<div class="d-flex flex-column">
		  <p class="m-auto p-2">
              ما دستور العمل لازم برای ریست کردن رمز عبور را برای شما ایمیل کردیم. اگر با ایمیلی که وارد کردید حساب کاربری موجود باشد، به زودی ایمیل را دریافت خواهید کرد.
		  </p>
		  <p class="m-auto p-2">
              اگر ایمیلی دریافت نکردید، لطفا از صحیح بودن آدرس ایمیل خود اطمینان حاصل و پوشه spam خود را چک کنید.
		  </p>
		  <p class="m-auto p-2"><a href="{% url 'home:home' %}">بازگشت به صفحه اصلی</a></p>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The CodingWithMitch Team
{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>
    {% block titel %}
        <title>فراموشی رمز عبور</title>
    {% endblock %}

<p class="text-center" style="margin-top: 100px">لطفا آدرس ایمیل خود را وارد کنید تا ایمیل حاوی نام کاربری و لینک ریست رمز عبور برای شما ارسال شود</p>
<form method="POST" class="form-signin text-center" style="margin-top: 100px">{% csrf_token %}
	<h1 class="h3 mb-3 font-weight-normal">ریست رمز عبور</h1>
    <input name="email" class="form-control" placeholder="آدرس ایمیل" type="email" id="id_email" required="true">
	<button class="btn btn-lg btn-primary btn-block" type="submit">ارسال ایمیل</button>
</form>



{% endblock %}

accounts/templates/accounts/password_reset_pass_form.html
{% extends 'base.html' %}

{% block content %}
    {% block titel %}
        <title>ریست رمز عبور</title>
    {% endblock %}
    <div class="d-flex flex-column justify-content-center" style="margin-top: 100px">
    <form method="POST" class="form-signin text-center m-auto">{% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">ریست رمز عبور</h1>
        <input name="new_password1" class="form-control m-1" placeholder="رمز عبور جدید" type="password" id="id_new_password1" required="true">
        <input name="new_password2" class="form-control m-1" placeholder="تایید رمز عبور جدید" type="password" id="id_new_password2" required="true">

        {% for field in form %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        {% endfor %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">تایید</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/profile_base.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <head>
        <title>پنل کاربری</title>
        <link rel="stylesheet" href="{% static 'css/profile_base_sidebar.css' %}">
    </head>

    <div class="container" style="bottom: 0;">
            {% block profile_content %}
            {% endblock %}
    </div>

    <!-- <script src="{% static 'js/profile_base_sidebar.js' %}"></script> -->
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
    {% block titel %}
        <title>ثبت نام</title>
    {% endblock %}
    <style>
        .form-signup {
          max-width: 340px;
          padding: 15px;
        }
        .form-signup:focus-within {
          z-index: 2;
        }
        .button-signup {
            max-width: 340px
        }
        
    </style>
    <div class="d-flex flex-column justify-content-center" style="margin-top: 100px">
        <main class="form-signup w-100 m-auto text-center" style="width: 100%">
            <h5 class="mb-3 fw-normal text-center">ثبت نام</h5>
            <hr class="login-register-hr">
            <form class="" method="post" style="width: 100%">
                {% csrf_token %}
                
                {% render_field form.email class="form-control my-2" placeholder="ایمیل" %}
                <small class="my-2" style="color: red;">{{ form.email.errors }}</small>
                
                {% render_field form.password1 class="form-control my-2" placeholder="رمز عبور" %}
                <small class="my-2" style="color: red; list-style: none;">{{ form.password1.errors }}</small>

                {% render_field form.password2 class="form-control my-2" placeholder="تکرار رمز عبور" %}
                <small class="my-2" style="color: red;">{{ form.password1.errors }}</small>

                <small class="my-2" style="color: gray;">{{ form.password1.help_text }}</small>
                <div class="captcha-field">
                    {% render_field form.captcha class="form-control form-sm my-2" placeholder="لطفا کد امنیتی را وارد کنید" %}
                    <small class="my-2" style="color: red; list-style: none;">{{ form.captcha.errors }}</small>
                </div>
                <button type="submit" class="btn btn-primary button-signup w-100 mt-2">ثبت نام</button>

                <a href="{% url 'accounts:user_login' %}" class="btn btn-outline-secondary w-100 mt-2">ورود به حساب کاربری</a>
            </form>
        </main>
    </div>

    

{% endblock %}

accounts/templates/accounts/user_profile.html
{% extends 'accounts/profile_base.html' %}

{% block profile_content %}
    {% block titel %}
        <title>حساب کاربری</title>
    {% endblock %}
    <style>
        .course-link{
            margin-right: auto;
        }
    </style>
    <div class="d-flex flex-column justify-content-center" style="padding: 2% 6%;">
        <section id="account-information" class="d-flex flex-column">
            <h5 class="text-center">پنل کاربری</h5>
            {% if uncomplete_info %}
                <h5 class="text-center text-danger my-2">لطفا برای نمایش داده شدن در وبسایت اطلاعات خود را <a href="{% url 'accounts:account_edit' %}">تکمیل</a> کنید.</h5>
            {% endif %}
            <p><i class="bi bi-person"></i> نام کاربری : {{ user.username|default:""  }}</p>
            <p><i class="bi bi-telephone"></i>شماره تلفن همراه : {{ user.phone_number|default:""  }}</p>
            <p><i class="bi bi-envelope"></i>آدرس ایمیل : {{ user.email }}</p>
            <p>نام : {{ user.first_name|default:"" }}</p>
            <p>نام خانوادگی : {{ user.last_name|default:""  }}</p>
            {% if user.is_teacher %}
                <p>مهارت : {{ user.skill|default:""  }}</p>
                <p>توضیحات : {{ user.description|default:""  }}</p>
            {% endif %}
        </section>
        <hr>
        {% if courses %}
            {% for course in courses %}
                <div class="d-flex flex-row card p-2 align-items-center">
                    <p class="m-0">{{ course.title }}</p>
                    <a class="btn btn-primary course-link" target="_blank" href="{{ course.link }}">اتصال به کلاس</a>
                </div>
            {% endfor %}
        {% endif %}

{% endblock %}