home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

skills/urls.py
from django.urls import path
from . import views

app_name = 'skills'

urlpatterns = [
    path('', views.SkillsView.as_view(), name='skills_home'),
    path('skill_details/<int:skill_id>/<str:skill_slug>/', views.SkillDetailsView.as_view(), name="skill_details"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('you-are-finally-awake/', admin.site.urls), # Real admin URL
    path('captcha/', include('captcha.urls')), # django-simple-captcha urls
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('skills/', include('skills.urls', namespace='skills')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skills/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Skill(models.Model):

    name = models.CharField(max_length=250, null=True, blank=True)
    category = models.CharField(max_length=250, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to='images/skills/')
    slug = models.SlugField(null=True, blank=True, max_length=300, unique=True, allow_unicode=True)

    def get_absolute_url(self):
        return reverse('skills:skill_details', args=(self.id, self.slug))

skills/views.py
from django.shortcuts import render
from django.views import View
from . import models

# Create your views here.
class SkillsView(View):
    def setup(self, request, *args, **kwargs):
        # gets a particular teacher time
        self.skills_instance = models.Skill.objects.all()
        super().setup(request, *args, **kwargs)

    def get(self, request):
        context = {'skills': self.skills_instance}
        return render(request, 'skills/skills_home.html', context)
    
class SkillDetailsView(View):

    def setup(self, request, *args, **kwargs):
        self.skill_instance = models.Skill.objects.get(slug=kwargs['skill_slug'])

        super().setup(request, *args, **kwargs)

    def get(self, request, skill_id, skill_slug):
        context = {'skill':self.skill_instance}
        return render(request, 'skills/skill_details.html', context)

skills/templates/skills/inc/skills_home_carousel.html
<section class="carousel-section d-flex container">
    <div class="d-flex flex-column skill-feature-box col-lg-6 col-md-12 ">
        <!-- <i class="bi bi-hand-index-thumb-fill" style="font-size: 4.5rem; color: white;"></i> -->
        <h5 class="feature_title text-light">مهارت مورد نظر خود را انتخاب کنید</h5>
        <p class="text-light">در این پلتفرم سعی بر این است که مهارت های متنوع برای یادگیری فراهم شوند</p>
        <a class="btn btn-secondary" href="{% url 'skills:skills_home' %}">تمام مهارت ها</a>
    </div>
    {% if skills %}
        <div class="carousel-div col-lg-6 col-md-12">
            <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel" style="width: 100%; height: 100%;">
                <div class="carousel-inner">
                    {% for skill in skills %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <img src="{{skill.image.url}}" class="d-block img-fluid skill-carousel-image w-100" alt="...">
                            <div class="skill-image-mask"></div>
                            <div class="carousel-caption">
                                <a class="skill-name btn btn-dark" href="{{ skill.get_absolute_url }}"><h5>{{ skill.name }}</h5></a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    {% endif %} 
</section>


<style>
    .skill-feature-box{
        justify-content:center; 
        align-items: start;
        padding-left: 4%;
    }
    .carousel-section {
        background-color: #277E9C;
        flex-direction: row;
        flex-wrap: wrap;
    }
    .skill-carousel-image{
        height: 300px;
        width: auto;
        object-fit: cover;
    
    }
    .carousel-inner{
        justify-content: center;
        height: 100%;
    
    }
    .skill-image-mask{
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 300px;
    
        background: linear-gradient(0deg, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0) 50%);
    }
    .carousel-caption{
        /* position: absolute; */
        /* width: 100%; */
        /* background: linear-gradient(90deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.6) 20%, rgba(0, 0, 0, 0.6) 80%, rgba(0, 0, 0, 0) 100%); */
        
    }
    .skill-name {
        text-decoration: none;
    
    }
    .carousel-item{
        object-fit: contain;
        height: 100%;
        
    }
    
    .carousel {
        object-fit: contain;

    }
    .carousel-control-prev{
        background: linear-gradient(90deg, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0) 90%);
        

    }
    .carousel-control-next{
        background: linear-gradient(90deg, rgba(0, 0, 0, 0) 10%, rgba(0, 0, 0, 1) 100%);
        

    }

    @media (max-width: 991px){
        .skill-feature-box{
            justify-content:center; 
            align-items: start;
        }
        .carousel-section{
            flex-direction: column-reverse;
        }
        .skill-carousel-image{

            height: 300px;
            width: auto;
            object-fit: cover;
            
        }
    }
</style>