home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name="cart"),
    path('remove_item/<int:item_id>/', views.removeItem.as_view(), name="remove_item"),
    path('order_complete/<int:order_id>', views.OrderCompleteView.as_view(), name="order_complete"),
    path('orders/', views.UserOrdersView.as_view(), name='user_orders'),
    path('transaction_info/<int:order_id>', views.TransactionInfoView.as_view(), name="transactionInfo"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('you-are-finally-awake/', admin.site.urls), # Real admin URL
    path('captcha/', include('captcha.urls')), # django-simple-captcha urls
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('skills/', include('skills.urls', namespace='skills')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.conf import settings
from courses import models as coursesModels


class Order(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="orders")
    date_ordered = models.DateTimeField(auto_now_add=True)
    status_choices = {('c', 'complete'), ('p', 'pending'), ('i', 'incomplete')}
    status = models.CharField(choices=status_choices, max_length=100, null=True, blank=True, default="incomplete")
    total = models.BigIntegerField(null=True)
    courseId = models.CharField(max_length=400, null=True, blank=True)

    def __str__(self):
        return f"{self.student} - status:{self.status}"


class Transaction(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, related_name="Transaction")

    date = models.CharField(max_length=100, null=True, blank=True)
    hour = models.CharField(max_length=100, null=True, blank=True)
    minute = models.CharField(max_length=100, null=True, blank=True)

    dateIssued = models.DateTimeField(auto_now_add=True)

    amount = models.FloatField(null=True, blank=True)
    card4Digits = models.CharField(max_length=4, null=True, blank=True)
    transactionId = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return f"{self.order} - {self.amount} - {self.date} - {self.hour}"

shop/forms.py
from django import forms
from . import models
from django.utils.translation import gettext_lazy as _


class TransactionInfoForm(forms.ModelForm):

    class Meta:

        model = models.Transaction
        fields = ('date', 'hour', 'minute', 'card4Digits', 'transactionId', 'amount')

        labels = {
            'date': _('تاریخ پرداخت'),
            'hour': _('ساعت'),
            'minute': _('دقیقه'),
            'card4Digits': _('چهار رقم پایانی کارت پرداخت کننده'),
            'transactionId': _('شماره پیگیری یا کد رسید'),
            'amount': _('مبلغ پرداخت شده'),
        }
        widgets = {
            'date': forms.TextInput(attrs={'class': 'form-control my-3', 'required':'true'}),
            'hour': forms.TextInput(attrs={'class': 'form-control my-3', 'required':'true'}),
            'minute': forms.TextInput(attrs={'class': 'form-control my-3', 'required':'true'}),
            'card4Digits': forms.TextInput(attrs={'class': 'form-control my-3', 'required':'true'}),
            'transactionId': forms.TextInput(attrs={'class': 'form-control my-3', 'required':'true'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control my-3', 'required':'true'}),
        }

shop/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .models import *
from . import forms

class CartView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            order = request.user.orders.get(status='incomplete')

        except Order.DoesNotExist:
            order = None

        context = {'order': order}
        return render(request, 'shop/cart.html', context)


class removeItem(LoginRequiredMixin, View):
    def get(self, request, item_id):
        order_item = OrderItem.objects.get(id=item_id)
        order_item.delete()
        messages.success(request, "کلاس با موفقیت حذف شد", 'success')
        return redirect('shop:cart')


class OrderCompleteView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'

    def get(self, request, order_id):
        ## this whole section is gonna change because we want to complete the orders by hand in admin panel
        if not request.user.username or not request.user.first_name or not request.user.last_name or not request.user.phone_number:
            messages.error(request, "لطفا اطلاعات کاربری خود را در قسمت ویرایش اطلاعات کاربری کامل کنید", 'danger')
            return redirect('accounts:account_details')
        else:
            try:
                order = Order.objects.get(id=order_id)
                order.complete = True
                order.save()
                order_items = order.order_orderItems.all()
                ## already_reserved is because we want to show an error is some teacherTimes were already reserved before user reserve them
                already_reserved = False
                for item in order_items:
                    if not item.teacherTime.is_reserved:
                        item.teacherTime.student = request.user
                        item.teacherTime.is_reserved = True
                        item.teacherTime.save()
                    else:
                        already_reserved = True
                if already_reserved == True:
                    messages.error(request, "تعدادی از جلسات انتخابی از قبل رزور شده اند", 'danger')
                    return redirect('accounts:user_profile')
                else:
                    messages.success(request, "جلسات انتخابی با موفقیت رزرو شدند", 'success')
                    return redirect('accounts:user_profile')
            except Order.DoesNotExist:
                messages.success(request, "سفارش یافت نشد", 'danger')
                return redirect('shop:cart')

                
class UserOrdersView(LoginRequiredMixin, View):

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request):
        try:
            orders = Order.objects.filter(student=request.user)
        except:
            orders = None
        context = {'orders': orders}
        return render(request, 'shop/user_orders.html', context)
                


class TransactionInfoView(View, LoginRequiredMixin):

    form_class = forms.TransactionInfoForm
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    
    def setup(self, request, *args, **kwargs):
        self.order_instance = Order.objects.get(id=kwargs['order_id'])
        return super().setup(request, *args, **kwargs)
    
    def get(self, request, order_id):
        order = self.order_instance
        form = self.form_class()
        context = {}
        context['form'] = form
        context['order'] = order
        return render(request, 'shop/transaction_info.html', context)
    
    def post(self, request, order_id):
        order = self.order_instance
        form = self.form_class(request.POST)
        context = {}
        context['form'] = form
        context['order'] = order
        if form.is_valid():
            transaction = form.save(commit=False)
            transaction.order = order
            transaction.save()
            order.status = 'pending'
            order.save()
            messages.success(request, "اطلاعات شما با موفقیت وارد شدند", 'success')
            return redirect('accounts:user_profile')
        
        return render(request, 'shop/transaction_info.html' , context)

shop/templates/shop/cart.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
{% block title %}
    <title>
        سبد خرید
    </title>
{% endblock %}
<style>
    .cart-section{
        margin-top: 71px;
    }
</style>
<section class="cart-section">
    <div class="dflex flex-column">
        <div class="d-flex justify-content-center">
            <div class="col-1" style="margin-left: auto">
                <input class="btn btn-outline-dark mx-2 mt-2" type=button value="&#8594; بازگشت" onClick="javascript:history.go(-1);">
            </div>
            <div class="col-2 position-absolute" style="justify-self: center">
                <h5 class="text-center my-2 m-auto">سبد خرید</h5>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-lg-6 mx-3" style="max-height: 690px">
            {% if order %}
                <div class="card my-2" style="border-radius: 0.3em; box-shadow: 0 4px 5px 0px rgba(0,0,0,0.1), 0 1px 0px 0px rgba(0,0,0,0.2)">
                    <div class="card-body text-center">
                        <div class="d-flex flex-column">
                            <p class="">دوره : {{ order.course.title }}</p>
                            <p class="">تعداد جلسات : {{ order.sessions_number }}</p>
                        </div>
                    </div>
                </div>
                {% else %}
                <h6 class="text-center">سبد خرید شما خالی است.</h6>
            {% endif %}
            </div>
            <div class="col-5 mx-3 my-2">
                <div class="card">
                    <div class="card-body">
                        {% if order.total %}
                        <h6>هزینه کل: {{ order.total|floatformat:"-3g" }} ریال</h6>
                            {% else %}
                            <h6>هزینه کل : 0 ریال</h6>
                        {% endif %}
                        <input class="col-3 m-auto my-3" name="discount" placeholder="کد تخفیف">
                        {% if order %}
                        <a href="" class=" btn btn-outline-primary btn-sm"> اعمال تخفیف</a>
                            {% else %}
                            <a href="" class=" btn btn-outline-primary btn-sm disabled"> اعمال تخفیف</a>
                        {% endif %}
                        <hr>
                        {% if order %}
                        <a href="{% url 'shop:transactionInfo' order.id %}" class="btn btn-primary my-3">پرداخت</a>
                            {% else %}
                            <a href="" class="btn btn-primary my-3 disabled">پرداخت</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

shop/templates/shop/transaction_info.html
{% extends 'base.html' %}


{% block content %}
<div class="d-flex flex-row container" style="background-color: #222831; height: 100%;">
    <div class="d-flex flex-column col-lg-4 p-2">
        <div class="d-flex flex-column p-2" style="border-radius: 8px; background-color: white;">
            <h4 class="text-center my-2"> مبلغ {{order.total|floatformat:"-3g"}} ریال</h4>
            <h5 class="text-center my-2"> به شماره کارت بانک ملی به نام خشایار خسروسورمی</h5>
            <h4 class="text-center my-2" style="direction: ltr; color: green;">6037 9917 7972 5039</h4>
            <h5 class="my-5">حتما پس از پرداخت برای اتمام مراحل ثبت سفارش، مشخصات پرداخت خود را به همراه شماره پیگیری یا کد رسید در فرم ثبت پرداخت وارد نمایید.</h5>
        </div>
    </div>
    <div class="d-flex flex-column col-lg-8 p-2">
        <div class="d-flex flex-column p-2" style="border-radius: 8px; background-color: white;">
            <form class="p-2" action="" method="post">{% csrf_token %}
                <h5 class="text-center">فرم ثبت پرداخت</h5>
                {{form.as_p}}
                <button class="btn btn-primary" type="submit">ثبت پرداخت</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}
    

shop/templates/shop/user_orders.html
{% extends 'accounts/profile_base.html' %}

{% block profile_content %}
    
    {% if orders %}
        
        {% for order in orders %}
            <div class="card">
                <div class="card-body d-flex flex-row" style="flex-wrap: wrap;">
                    <p class="px-5">تاریخ سفارش : {{order.date_ordered}}</p>
                    <p class="px-5">مبلغ کل : {{order.total}}</p>
                    
                    {% if order.status == 'complete' %}
                        <p class="px-5" style="background-color: green; color: white;">وضعیت سفارش : تکمیل شد</p>
                    {% elif order.status == 'pending' %}
                        <p class="px-5" style="background-color: yellow;">وضعیت سفارش : در حال بررسی</p>
                        {% else %}
                        <p class="px-5" style="background-color: red;">وضعیت سفارش : ناتمام</p>
                    {% endif %}

                </div>
            </div>
        {% endfor %}
    {% else %}
            <p>سفارشی یافت نشد</p>
    {% endif %}
        
{% endblock %}