accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='user_registration'),
    path('login/', views.LoginView.as_view(), name='user_login'),
    path('logout/', views.LogoutView.as_view(), name='user_logout'),
    path('user_profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('edit/', views.AccountEditView.as_view(), name='account_edit'),

    # password reset urls
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),

    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_pass_form.html'), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'),
         name='password_reset',),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view
         (template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

]

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.CoursesView.as_view(), name="home"),
    path('search', views.CoursesSearchView.as_view(), name="search"),
    path('course_details/<int:course_id>', views.CourseDetailsView.as_view(), name="course_details"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name="cart"),
    path('remove_item/<int:item_id>/', views.removeItem.as_view(), name="remove_item"),
    path('order_complete/<int:order_id>', views.OrderCompleteView.as_view(), name="order_complete"),
    path('orders/', views.UserOrdersView.as_view(), name='user_orders'),
    path('transaction_info/<int:order_id>', views.TransactionInfoView.as_view(), name="transactionInfo"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('you-are-finally-awake/', admin.site.urls), # Real admin URL
    path('captcha/', include('captcha.urls')), # django-simple-captcha urls
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('skills/', include('skills.urls', namespace='skills')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/inc/account_details_sidebar.html
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'account_details' %}">
              <span data-feather="home" class="align-text-bottom"></span>
              پنل کاربری
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'time_checkbox' %}">
              <span data-feather="file" class="align-text-bottom"></span>
              تایم های خالی من
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_edit' %}">
              <span data-feather="shopping-cart" class="align-text-bottom"></span>
              ویرایش اطلاعات
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users" class="align-text-bottom"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2" class="align-text-bottom"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers" class="align-text-bottom"></span>
              Integrations
            </a>
          </li>
        </ul>
      </div>
    </nav>

templates/inc/course_cards.html
<div class="container-fluid p-2" style="background-color: #14436b">
    <h4 class="text-center text-light mt-3">دوره های محبوب ما</h4>
    <div class="row justify-content-center mb-3">
        {% for c in courses %}
        <div class="col-lg-3 col-md-4 col-sm-4 m-4">
            <div class="card text-center" style="box-shadow: 0 3px 10px rgba(0, 0, 0, 0.15)">
                    <div class="card-header">
                        <h4>{{ c.title }}</h4>
                    </div>
                    <div class="card-body" style="height: 100px">
                        <p class="card-text text-center">{{ c.description}}</p>
                    </div>
                    <div class="card-footer">
                        <a href="" class="btn">SignUp</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="d-flex flex-column mb-3 p-0 justify-content-center">
        <a href="" class="btn btn-outline-light m-auto" style="font-size: larger">لیست کامل دوره ها</a>
    </div>
</div>

templates/inc/courses_search_bar.html
<style>
    .search-bar .btn-primary{
        width: 150px;
        margin-left: 5px;
    }

    .search-bar-input-danger{
        border-color: red;
    }
    .search-bar .form-control {
        transition: 300ms border-color;
    }
</style>
<form action="{% url 'courses:search' %}" method="POST">
    {% csrf_token %}
    <section class="search-bar">
        <div class="d-flex flex-row">
            <button id="submitButton" class="btn btn-primary"><i class="bi bi-search"></i> جستجو</button>
            <input id="inputField" class="form-control form-control-lg" name="courses-search" type="text" placeholder="جستجو دوره ها" aria-label=".form-control-lg example">
        </div>
    </section>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
        const inputField = document.getElementById('inputField');
        const submitButton = document.getElementById('submitButton');
        const errorMessage = document.getElementById('errorMessage');

        submitButton.addEventListener('click', function(event) {
            if (inputField.value.trim() === '') {
                event.preventDefault();
                inputField.classList.add('search-bar-input-danger')
            } else {
                inputField.classList.rmeove('search-bar-input-danger')
            }
        });
    });
    </script>
    
</form>

templates/inc/features.html
{% load static %}

<section id="features" class="d-flex justify-content-center background-dark">
    <div class="container row justify-content-between">
        <div class="feature-box col-lg-3">
            <i class="bi bi-hand-index-thumb-fill feature-icon"></i>
            <h5 class="feature_title text-light">از بین اساتید مهارت دلخواهتان انتخاب کنید</h5>
            <p class="text-light">در این پلتفرم سعی بر این است که مهارت های متنوع برای یادگیری فراهم شوند</p>
        </div>
        <div class="feature-box col-lg-3">
            <i class="bi bi-calendar-week-fill feature-icon"></i>
            <h5 class="feature_title text-light">با توجه به برنامه استاد روز و ساعت دلخواه و همینطور تعداد جلسات را معین کنید</h5>
            <p class="text-light">بر اساس ساعت و روز انتخابی به صورت خودکار جلسات شما تنظیم خواهند شد</p>
        </div>
        <div class="feature-box col-lg-3">
            <i class="bi bi-book-half feature-icon"></i>
            <h5 class="feature_title text-light">در هر مکان به یادگیری آنلاین دسترسی داشته باشید</h5>
            <p class="text-light">جلسات و سفارشات شما در پنل کاربری قابل دسترسی هستند</p>
        </div>
    </div>
</section>

<style>

    #features .container {
        padding: 6% 8%;
    }
    .feature_title {
    margin-top: 5%;
    }

    .feature-box {
        text-align: center;
        padding: 0;
    }
    .feature-icon{
        font-size: 4.5rem;
        color: white;
    }
</style>

templates/inc/footer.html
<div id="footer" class="d-flex flex-row container text-light justify-content-between align-items-center">
    <div class="d-flex flex-column p-2">
        <!-- <p><a href="https://www.instagram.com/class.iran/" target="_blank" style="color: white; text-decoration: none;"><i class="bi bi-instagram" style="font-size: 3rem;"></i></a></p> -->
        <p></p>
    </div>
    <div class="d-flex flex-column p-2">
        <p>ساخته شده توسط تیم کلاس ایران</p>
    </div>
</div>
<style>
    #footer {
        background-color: #333333;
    }
</style>

templates/inc/hero.html
{% load static %}

<style>
    .hero {
        height: 100vh;
    }
    .hero-text-container {
        margin-top: 120px;
    }
    .home-background{
        z-index: -1;
        position: absolute; 
        width: 100%; 
        height: 100%; 
        object-fit: fill;
    }
    

    @media (max-width: 991px){
        .hero .d-flex {
            flex-direction: column;
        }
    }
</style>

<section class="hero d-flex flex-column align-items-center">
    <img class="home-background img-fluid" src="{% static 'img/home-background.png' %}" alt="">
    <div class="hero-text-container d-flex container justify-content-center align-items-center">
        <div class="d-flex flex-column jumbotron-text-btn col-lg-6 align-items-start justify-content-center">
            <h3 class="text-center mb-3">با پلتفرم یادگیری قدرتمند ما، پتانسیل های خود را کشف کنید.</h3>
            <h5 class="text-center">اساتید مجرب و دوره های متنوع این وبسایت، تجربه‌ی جدیدی از یادگیری آسان و اقتصادی را برای شما فراهم خواهند کرد.</h5>
        </div>    
    </div>
    {% include 'inc/courses_search_bar.html' %}
    {% include 'inc/social_media_links.html' %}
</section>

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }} m-auto" style="border-radius: 0; height: max-content">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg justify-content-center">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home:home' %}">کلاس ایران</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:home' %}">دوره ها</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">راهنما</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:cart' %}"><i class="bi bi-basket3" style="font-size: 1.5rem;"></i></a>
                </li>
            </ul>
        </div>      
        {% if user.is_authenticated %}
            <div class="dropdown-center">
                <button type="button" class="dropdown-toggle-split" style="border: none; background-color: transparent;" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person-circle text-light" style="font-size: 1.5rem;"></i></button>
                <ul class="dropdown-menu dropdown-menu-left">
                    <li class="dropdown-item">
                        <a class="nav-link dropdown-link" href="{% url 'accounts:user_profile' %}"><i class="bi bi-person-lines-fill mx-2"></i>پنل کاربری</a>
                    </li>
                    {% if user.is_teacher %}
                        <li class="dropdown-item">
                            <a class="nav-link dropdown-link" href="{% url 'courses:time_checkbox' %}"><i class="bi bi-calendar-check mx-2"></i> تایم های خالی من</a>
                        </li>
                    {% endif %}
                    <li class="dropdown-item">
                        <a class="nav-link dropdown-link" href="{% url 'shop:user_orders' %}"><i class="bi bi-card-heading mx-2"></i> سفارش های من</a>
                    </li>
                    <li class="dropdown-item">
                        <a class="nav-link dropdown-link" href="{% url 'accounts:account_edit' %}"><i class="bi bi-pencil-square mx-2"></i>ویرایش اطلاعات کاربری</a>
                    </li>
                    <li class="dropdown-item">
                        <a class="nav-link dropdown-link" href="{% url 'accounts:password_change' %}"><i class="bi bi-key mx-2"></i>تعویض رمز عبور</a>
                    </li>
                    <li><hr class="dropdown-divider-dark" ></li>
                    <li class="dropdown-item">
                        <a class="nav-link dropdown-link" href="{% url 'accounts:user_logout' %}"><i class="bi bi-box-arrow-right mx-2"></i>خروج</a>
                    </li>
                </ul>
            </div>   
        {% else %}
            <li class="nav-item list-unstyled">
                <a class="login-btn btn btn-outline-dark" href="{% url 'accounts:user_registration' %}" style="margin-right: 8px;">ثبت نام | ورود</a>
            </li>
        {% endif %}
    </div>
</nav>

<style>
    .navbar {
        padding: 0;
        position: fixed;
        width: 100vw;
        transition: background-color 0.3s ease-in-out;
        z-index: 1000;
        background-color: transparent;
    }
    .navbar-scrolled {
        background-color: rgba(241, 241, 241, 0.96) !important;
    }
    .navbar .container {
        padding: 1% 8%;
    }
    .navbar .dropdown-menu .bi {
        font-size: 1.3rem;
    }
    .navbar-brand{
        margin: auto 0;
        color: var(--color-brand-3);
        font-weight: 500;
    }
    .navbar-brand:hover{

        color: var(--color-brand-3);
    }

    .nav-link{
        color: black;
    }
    .dropdown-link[aria-current="page"]{
        background-color: #00A5DB;
        color: white;

    }
    .dropdown-item {
        padding-right: 0;
        padding-left: 0;
        justify-content: center;
    }
    .dropdown-link {
        text-align: right;
        padding: 3%;
        align-items: center;
        display: flex;
        flex-direction: row;

    }
    .dropdown-divider-dark {
        padding: 0;
        margin: 0;
    }
    .dropdown-menu {
        box-shadow: 5px 10px 10px 5px rgba(0, 0, 0, 0.4);
        min-width: 210px;
    }
    .bottom-bar-button:hover{
        background: linear-gradient(0deg, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0) 50%);
        transition: background 300ms ease;
    }

    .login-btn{
        background-color: rgba(255, 255, 255, 0.75);
    }

    .navbar-collapse .navbar-nav .nav-item {
        margin: 0 1rem;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .navbar-collapse .navbar-nav .nav-item .nav-link {
        margin: 0;
    }
    .navbar .container .navbar-collapse .navbar-nav {
        margin-right: auto;
    }
    .navbar-toggler {
        margin-right: auto;
    }

    .bi-person-circle{
        transition: color 0.3s ease-in-out;
    }
    .bi-person-circle-dark {
        color: black;
    }
</style>
 <script>
    //the current page color change for the drop down menu
    document.querySelectorAll('.dropdown-link').forEach(link => {
        if(link.href === window.location.href){
            link.setAttribute('aria-current', 'page')
        }
    })

    //to make user icon white in homepage and black in other pages
    // document.addEventListener('DOMContentLoaded', function() {
    //     // Check if the current page is the homepage
    //     if (window.location.pathname !== '/' || window.location.pathname !== '/base.html') {
    //         // Add the specific class to the icon
    //         document.getElementById('bi-person-circle').classList.add('bi-person-circle-dark');
    //     }
    // });


    // navbar background change with scroll script  
    // Listen for the scroll event
    window.addEventListener("scroll", () => {
        const navbar = document.querySelector(".navbar");
        const login_icon = document.querySelector(".bi-person-circle")

        // Check if the page has scrolled a certain amount of pixels (e.g., 100px)
        if (window.scrollY >= 100) {
            // If scrolled, add the "scrolled" class to the navbar
            navbar.classList.add("navbar-scrolled");
            login_icon.classList.remove("text-light")

        } else {
            // If not scrolled enough, remove the "scrolled" class from the navbar
            navbar.classList.remove("navbar-scrolled");
            login_icon.classList.add("text-light");
        }
    });
 </script>

templates/inc/profile_base_sidebar.html
<nav class="hidden d-md-block sidebar collapse"
     style="background: white; box-shadow: -1px 0 5px 0 rgba(0,0,0,0.1); height: 100%;">
      <div class="sidebar-sticky" id="sidebarNav">
        <ul class="nav flex-column" style="padding: 0.8rem;">
          <li class="nav-item" style="margin-left: auto">
            <a class="nav-link sidebar-link text-start" href="{% url 'accounts:account_details' %}" style="font-size: 1rem; padding: 0;">
              پنل کاربری
            </a>
          </li>
          <hr>
          {% if user.is_teacher %}
            <li class="nav-item">
              <a class="nav-link sidebar-link" href="{% url 'courses:time_checkbox' %}" style="font-size: 1rem; padding: 0;">
                تایم های خالی من
              </a>
            </li>
            <hr>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link sidebar-link" href="{% url 'accounts:account_edit' %}" style="font-size: 1rem; padding: 0;">
              ویرایش اطلاعات کاربری
            </a>
          </li>
          <hr>
          <li class="nav-item">
            <a class="nav-link sidebar-link" href="{% url 'accounts:password_change' %}" style="font-size: 1rem; padding: 0;">
              تعویض رمز عبور
            </a>
          </li>
          <hr>
          <li class="nav-item">
            <a class="nav-link sidebar-link" href="{% url 'shop:user_orders' %}" style="font-size: 1rem; padding: 0;">
              سفارش های من
            </a>
          </li>
        </ul>
      </div>
    </nav>

templates/inc/social_media_links.html
<style>
    .social-media-links{
        margin-top: 50px;
    }
    .social-link-container {
        border-radius: 100%;
        width: 100px;
        height: 100px;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        margin: 4%;
        overflow: hidden;
        
    }

    .social-link{
        padding: 0;
        margin: 0;
        color: white;
        text-decoration: none;
        position: absolute;
    }
    .social-icon{
        font-size: 3rem;
        color: var(--color-brand-3);
    }
    .social-icon:hover{
        font-size: 3.5rem;
        transition: 100ms;
    }
    
</style>
<section class="social-media-links container d-flex flex-row justify-content-center">
    <div class="social-link-container d-flex">
        <a class="social-link" href="https://www.instagram.com/class.iran/" target="_blank"><i class="bi bi-instagram social-icon"></i></a>
    </div>
    <div class="social-link-container d-flex">
        <a class="social-link" href="#" target="_blank"><i class="bi bi-whatsapp social-icon"></i></a>
    </div>
    <div class="social-link-container d-flex">
        <a class="social-link" href="#" target="_blank"><i class="bi bi-telegram social-icon"></i></a>
    </div>
</section>
    